@echo off
REM ------------------------------------------------------
REM --------       Teo's mysql dump script        --------
REM ------------------------------------------------------
set dumpExe="C:\Program Files\MySQL\MySQL Server 5.6\bin\mysqldump.exe"
set mysqlhost=localhost
set mysqluser=root
set mysqlpass=Ir0nd00r
set LogPath=G:\MySQLBackups\logs
for /f "tokens=1" %%i in ('date /t') do set DATE_DOW=%%i
for /f "tokens=2" %%i in ('date /t') do set DATE_DAY=%%i
for /f %%i in ('echo %date_day:/=-%') do set DATE_DAY=%%i
for /f %%i in ('time /t') do set DATE_TIME=%%i
for /f %%i in ('echo %date_time::=-%') do set DATE_TIME=%%i
for /f %%i in ('time /t') do set START_TIME=%%i
for /f %%i in ('echo %start_time::=:%') do set START_TIME=%%i
CLS
ECHO Backup Started Date: %DATE_DAY% Time: %START_TIME%
IF NOT EXIST G:\MySQLBackups\gamer_server\ md G:\MySQLBackups\gamer_server\
IF NOT EXIST G:\MySQLBackups\gamer_server\7z\ md G:\MySQLBackups\gamer_server\7z\
IF NOT EXIST G:\MySQLBackups\gamer_server\temp\ md G:\MySQLBackups\gamer_server\temp\
IF NOT EXIST G:\MySQLBackups\gamer_server\7z\%DATE_DAY%_%DATE_TIME%\ md G:\MySQLBackups\gamer_server\7z\%DATE_DAY%_%DATE_TIME%\
IF NOT EXIST G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\ md G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\
ECHO Dumping game server DB tables's..
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb accounts > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\accounts.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_effects > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_effects.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_equip > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_equip.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_exp > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_exp.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_inventory > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_inventory.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_jobs > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_jobs.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_look > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_look.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_merit > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_merit.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_pet_name > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_pet_name.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_points > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_points.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_profile > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_profile.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_skills > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_skills.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_stats > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_stats.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_storage > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_storage.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_spells > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_spells.sql"
REM (doesn't exist anymore/yet?) %dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_titles > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_titles.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_vars > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_vars.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb char_weapon_skill_points > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\char_weapon_skill_points.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb chars > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\chars.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb delivery_box > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\delivery_box.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb linkshells > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\linkshells.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb server_variables > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\server_variables.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb zone_settings > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\zone_settings.sql"
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% dspdb auction_house > "G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\auction_house.sql"
ECHO ..Done dumping tables. Now compressing SQL Files..
IF NOT EXIST G:\MySQLBackups\gamer_server\7z\%DATE_DAY%_%DATE_TIME%\ md G:\MySQLBackups\gamer_server\7z\%DATE_DAY%_%DATE_TIME%\
CALL "C:\Program Files\7-Zip\7z.exe" a -t7z -aoa -mx9 G:\MySQLBackups\gamer_server\7z\%DATE_DAY%_%DATE_TIME%\DB.7z G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\*.*
ECHO ..DONE. Now deleting Temp SQL Files..
@rmdir G:\MySQLBackups\gamer_server\temp\%DATE_DAY%_%DATE_TIME%\ /S /q
ECHO ..DONE. Now backing up forum shiz.
IF NOT EXIST G:\MySQLBackups\forum\ md G:\MySQLBackups\forum\
IF NOT EXIST G:\MySQLBackups\forum\7z\ md G:\MySQLBackups\forum\7z\
IF NOT EXIST G:\MySQLBackups\forum\temp\ md G:\MySQLBackups\forum\temp\
IF NOT EXIST G:\MySQLBackups\forum\7z\%DATE_DAY%_%DATE_TIME%\ md G:\MySQLBackups\forum\7z\%DATE_DAY%_%DATE_TIME%\
IF NOT EXIST G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\ md G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\
ECHO Dumping forum DB tables's..
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_acl_groups > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_acl_groups.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_acl_options > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_acl_options.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_acl_roles > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_acl_roles.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_acl_roles_data > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_acl_roles_data.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_acl_users > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_acl_users.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_attachments > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_attachments.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_banlist > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_banlist.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_bbcodes > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_bbcodes.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_bookmarks > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_bookmarks.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_bots > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_bots.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_captcha_answers > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_captcha_answers.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_captcha_questions > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_captcha_questions.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_config > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_config.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_config_text > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_config_text.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_confirm > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_confirm.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_disallow > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_disallow.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_drafts > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_drafts.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_ext > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_ext.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_extension_groups > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_extension_groups.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_extensions > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_extensions.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_forums > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_forums.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_forums_access > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_forums_access.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_forums_track > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_forums_track.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_forums_watch > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_forums_watch.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_groups > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_groups.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_icons > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_icons.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_lang > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_lang.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_log > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_log.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_login_attempts > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_login_attempts.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_migrations > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_migrations.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_moderator_cache > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_moderator_cache.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_mods > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_mods.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_modules > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_modules.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_notification_types > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_notification_types.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_notifications > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_notifications.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_oauth_accounts > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_oauth_accounts.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_oauth_tokens > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_oauth_tokens.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_poll_options > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_poll_options.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_poll_votes > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_poll_votes.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_posts > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_posts.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_privmsgs > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_privmsgs.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_privmsgs_folder > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_privmsgs_folder.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_privmsgs_rules > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_privmsgs_rules.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_privmsgs_to > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_privmsgs_to.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_profile_fields > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_profile_fields.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_profile_fields_data > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_profile_fields_data.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_profile_fields_lang > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_profile_fields_lang.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_profile_lang > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_profile_lang.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_qa_confirm > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_qa_confirm.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_ranks > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_ranks.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_reports > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_reports.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_reports_reasons > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_reports_reasons.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_search_results > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_search_results.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_search_wordlist > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_search_wordlist.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_search_wordmatch > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_search_wordmatch.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_sessions > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_sessions.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_sessions_keys > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_sessions_keys.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_sitelist > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_sitelist.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_smilies > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_smilies.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_sortables_answers > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_sortables_answers.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_sortables_confirm > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_sortables_confirm.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_sortables_questions > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_sortables_questions.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_styles > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_styles.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_teampage > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_teampage.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_topics > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_topics.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_topics_posted > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_topics_posted.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_topics_track > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_topics_track.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_topics_watch > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_topics_watch.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_user_group > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_user_group.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_user_notifications > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_user_notifications.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_users > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_users.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_warnings > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_warnings.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_words > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_words.sql
%dumpExe% --lock-tables=false --skip-triggers --skip-extended-insert --order-by-primary --hex-blob --no-create-info --compact --skip-comments -h %mysqlhost% -u %mysqluser% -p%mysqlpass% legion_forums phpbb_zebra > "G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\phpbb_zebra.sql
ECHO ..Done dumping tables. Now compressing SQL Files..
IF NOT EXIST G:\MySQLBackups\forum\7z\%DATE_DAY%_%DATE_TIME%\ md G:\MySQLBackups\forum\7z\%DATE_DAY%_%DATE_TIME%\
CALL "C:\Program Files\7-Zip\7z.exe" a -t7z -aoa -mx9 G:\MySQLBackups\forum\7z\%DATE_DAY%_%DATE_TIME%\DB.7z G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\*.*
ECHO ..DONE. Now deleting Temp SQL Files..
@rmdir G:\MySQLBackups\forum\temp\%DATE_DAY%_%DATE_TIME%\ /S /q
ECHO ..DONE
for /f %%i in ('time /t') do set END_TIME=%%i
for /f %%i in ('echo %end_time::=:%') do set END_TIME=%%i
REM ------------------------------------------------------
echo Last Backup Run on %date% >> %LogPath%\log.txt
echo StartTime: %START_TIME% - EndTime: %END_TIME% >> %LogPath%\log.txt
ECHO Nuking vars
set dumpExe=
set mysqlhost=
set mysqluser=
set mysqlpass=
set LogPath=
ECHO All done! %DATE_DAY% StartTime: %START_TIME% - EndTime: %END_TIME%