-- ---------------------------------------------------------------------------
-- This file adds onto or modifies contents of item_latents.sql
-- and must be imported/executed AFTER that file
--
-- For new entries DarkStar does not have, use "INSERT INTO"
-- For changing entries that already exist use "REPLACE INTO"
-- REPLACE tells MySQL to delete the old line and insert the new one.
-- Using the wrong 1 of these 2 commands will result in errors.
-- ---------------------------------------------------------------------------

-- INSERT INTO `item_mods` VALUES (itemId,modId,value,latentId,latentParam); -- remember to comment what the item is and what this mod is!
-- New entries below this line, and sorted by itemID.
